### ISSUE TITLE
OKD SNO Bootstrap In Place fails to complete because of corrupted Journal file

### ISSUE THREAD

**Issue by cgruver** [okd-project/okd#1607]
**Describe the bug**
__Note:__ This is attempting an unattended, no-touch, install via iPXE.  This method does not use the assisted installer and boot from an attached ISO.

This install method is using two internal disks.  The first is the initial boot disk, the second is the install disk.

During the final phase of cluster installation, the Machine Configuration Operator fails to become healthy because of a corrupted Journal file.

The issue can be resolved by running the following on the cluster node:

```bash
sudo journalctl --rotate && sudo journalctl --vacuum-time=1s
```

After cleaning up the Journal files, the installation completes successfully.

**Version**
`4.12.0-0.okd-2023-04-16-041331`

**How reproducible**
100%

**Log bundle**
Issue is exactly like the bug reported here: [https://bugzilla.redhat.com/show_bug.cgi?id=1886207](https://bugzilla.redhat.com/show_bug.cgi?id=1886207)

**Comment by vrutkovs** [comment]
Its probably a Fedora bug too

**Comment by dustymabe** [comment]
I was able to observe this on a cluster I deployed yesterday. At least for that cluster we started on the latest FCOS (Fedora 38 based) and it was then switched back to F37. Maybe that could be part of the problem?

**Comment by cgruver** [comment]
That's exactly what this one is doing.  @dustymabe I suspected the same thing after getting more detailed error out of `journalctl`.  It was complaining about an unsupported feature in one of the Journal files.  I suspect because of the pivot from FCOS 38 back to 37.

**Comment by vrutkovs** [comment]
Oh, right, that'd explain it. Upcoming OKD 4.13 (and latest 4.12 nighlies) use F38 stable now

**Comment by dustymabe** [comment]
Well actually, the more I think about it this problem might actually not go away when OKD switches to F38. It may make it worse? It depends on what the actual problem is:

- Is the problem that going from 38 to 37 means that the journal (started on F38) has some invalid format and can't be read on F37?
- OR is it that there is a countainer with it's own version of `journalctl` (probably from CentOS Stream?) that is too old to read F38 written journals?

If it's the latter then moving to F38 as the base for OKD may make the problem worse and render the workaround mentioned in the description here useless.

**Comment by vrutkovs** [comment]
We don't use `journalctl` from any container, so I suspect its the former

**Comment by JaimeMagiera** [comment]
Hi,

We are not working on FCOS builds of OKD any more. Please see these documents...

https://okd.io/blog/2024/06/01/okd-future-statement
https://okd.io/blog/2024/07/30/okd-pre-release-testing

Please test with the OKD SCOS nightlies and file a new issue as needed.

Many thanks,

Jaime
