### ISSUE TITLE
Podman build in-container fails with the latest OKD 4.13 FCOS based builds

### ISSUE THREAD

**Issue by cgruver** [okd-project/okd#1656]
### Describe the bug

[https://github.com/eclipse/che/issues/22355](https://github.com/eclipse/che/issues/22355)

A recent update to either the OpenShift code base, or Fedora CoreOS has broken the ability to run `podman build` in a Che workspace.

The issue manifests after updating `4.13.0-0.okd-2023-06-04-080300` to version `4.13.0-0.okd-2023-06-24-145750`

The issue persists in nightly builds of FCOS based OKD 4.13

The issue does not appear in the latest SCOS based OKD 4.13

Suspect a recent change in FCOS.

### Che version

7.70@latest

### Steps to reproduce

Build a cluster with `4.13.0-0.okd-2023-06-24-145750`

Deploy Eclipse Che

Start a workspace enabled for container build

Run:

```bash
podman images
```

Observe the error:

```bash
cannot clone: Permission denied
Error: cannot re-exec process
```

### Expected behavior

Podman images returns a list of images, or empty if no images are present.

**Comment by forzamehlano** [comment]
We've run into this on 4.13.0-0.okd-2023-07-23-051208. After some digging we discovered an selinux failure when the pod ran:

`avc: denied { create } for pid=<PID> comm="exe" scontext=system_u,system_r,continer_t:s0:c5:c30 tcontext=system_u,system_r,container_t:s0:c5:c30 tclass=user_namespace permissive=0`

This looks very much like https://github.com/containers/container-selinux/issues/257 which was fixed in container_selinux 2.219 / fcos 38.20230709.03 / 4.13.0-0.okd-2023-08-04-164726.

Planning to test this in the coming days to confirm the podman build now works in the later OKD version

**Comment by forzamehlano** [comment]
Finally got round to testing this and can confirm this now  works in 4.13.0-0.okd-2023-09-30-084937

**Comment by cgruver** [comment]
Closing as resolved.
