### ISSUE TITLE
https://issues.redhat.com/browse/OCPBUGS-15087 broke OKD

### ISSUE THREAD

**Issue by cgwalters** [okd-project/okd#1768]
In https://issues.redhat.com/browse/OCPBUGS-15087 AKA https://github.com/openshift/machine-config-operator/pull/3865 we did a giant rework of the systemd units; it is believed that this broke OKD.

**Comment by cgwalters** [comment]
Digging into [this scos run](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-okd-scos-4.15-e2e-aws-ovn/1716213870168641536) we failed to provision control plane nodes at all. 

Kubelet started up, but looks like it failed to register with the bootstrap?  Logs are full of
```
Sun 2023-10-22 22:19:44 UTC ip-10-0-51-83 kubelet.service[2154]: E1022 22:19:44.582987    2154 kubelet_node_status.go:485] "Error getting the current node from lister" err="node \"ip-10-0-51-83\" not found"
```

**Comment by vrutkovs** [comment]
Tested this manually - seems on some nodes I need to do `systemctl daemon-reload` and restart kubelet service.

Also, in some installations nodes show up as `ip-10-0-51-83` instead of `ip-10-0-51-83.us-west-1.compute.internal` - perhaps some hostname/afterburn service in not included in kubelet-dependencies.target?

**Comment by cgwalters** [comment]
Ah this may be related to https://issues.redhat.com/browse/OCPBUGS-20369 since it's AWS

**Comment by vrutkovs** [comment]
Right, that seems to be AWS-specific indeed - I don't see this happening on GCP and comments in OCPBUGS-20369 seem to be similar to what I'm seeing
