### ISSUE TITLE
Bug: Style issue in all versions of docs

### ISSUE THREAD

**Issue by Afrin127329** [okd-project/okd#1926]
**Describe the bug**
In docs pages, there are serious styling issues with the contents, sidebar, top sections. All are messed up.. See the below example:

![okd](https://github.com/okd-project/okd/assets/125039325/0112f106-8de4-4aa7-b688-9bfc67bdce20)
![okd2](https://github.com/okd-project/okd/assets/125039325/4c8324df-fa71-4cd7-b82c-a616a0233826)

**Version**
Happening to all the versions

**How reproducible**
1. Open https://docs.okd.io/
2. Select any version from the dropdown, after the navigation you will see the problem I have shown in above screenshots.

**Comment by GingerGeek** [comment]
That's odd and I can't reproduce on my side.

What browser/OS are you using?

Do you see similar styling quirks on the Openshift build of the documentation?

https://docs.openshift.com/container-platform/4.15/welcome/index.html

**Comment by kai-uwe-rommel** [comment]
I can reproduce this - if the browser window is "narrow enough". The docs pages all look fine when I run the browser on my large main screen and the window is wide enough. I have an old secondary screen with only 1600x1200 and when I put Firefox with the sidebar open but otherwise maximised on this screen, I see the same mis-layout. So to reproduce on a large screen de-maximize the browser window and drag it narrower until you see the problem.

**Comment by GingerGeek** [comment]
Ah yeah, thanks for that I've replicated now

**Comment by Afrin127329** [comment]
> Do you see similar styling quirks on the Openshift build of the documentation?
> 
> https://docs.openshift.com/container-platform/4.15/welcome/index.html

Nope it's okay with openshift

**Comment by Afrin127329** [comment]
> And the problem apparently only affects the OKD documentation and not the original OCP documentation.

Exactly.

**Comment by Afrin127329** [comment]
> What browser/OS are you using?

Using firefox, screen size is 1349 × 615
